name: Verify Types
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: microsoft/playwright-github-action@v1
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16.1
      - name: Install Browsers
        run: go run scripts/install-browsers/main.go
      - name: Regenerate APIs
        run: scripts/generate-api.sh
      - name: Verify API is up to date
        run: git diff --exit-code --ignore-submodules